/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import type { Labradoodle } from './labradoodle';
import type { Dachshund } from './dachshund';

export type Dog = Labradoodle | Dachshund;
