/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */

export * from "./cat";
export * from "./catType";
export * from "./createPetsBodyItem";
export * from "./dachshund";
export * from "./dog";
export * from "./error";
export * from "./labradoodle";
export * from "./listPetsParams";
export * from "./pet";
export * from "./pets";
